version: '3'

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 030121034
      WORDPRESS_DB_NAME: vize
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 030121034
      MYSQL_DATABASE: vize
      MYSQL_USER: root
      MYSQL_PASSWORD: 030121034
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx:/etc/nginx/conf.d
      - wordpress:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email aydinnursena25@gmail.com --agree-tos --no-eff-email -d nursena.me
    depends_on:
      - nginx

volumes:
  wordpress:
  mariadb:
  nginx:
  certbot-etc:
  certbot-var:
