version: "3.8"
services:
  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=030121034
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=030121034
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=030121034
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost:/etc/nginx/vhost.d
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    environment:
      - DOMAINS=nursena.me
      - EMAIL=030121034@std.izu.edu.tr


volumes:
  wordpress_data:
  db_data:
